<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace buddy;

use \php\Boot;

class SingleSuite extends BuddySuite {
	/**
	 * @return void
	 */
	public function __construct () {
		#C:\HaxeToolkit\haxe\lib\buddy/2,10,2/buddy/SingleSuite.hx:6: characters 24-31
		parent::__construct();
	}
}

Boot::registerClass(SingleSuite::class, 'buddy.SingleSuite');
