<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace buddy;

use \php\Boot;
use \php\_Boot\HxEnum;

class TestFunc extends HxEnum {
	/**
	 * @param \Closure $f
	 * 
	 * @return TestFunc
	 */
	static public function Async ($f) {
		return new TestFunc('Async', 0, [$f]);
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return TestFunc
	 */
	static public function Sync ($f) {
		return new TestFunc('Sync', 1, [$f]);
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			0 => 'Async',
			1 => 'Sync',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'Async' => 1,
			'Sync' => 1,
		];
	}
}

Boot::registerClass(TestFunc::class, 'buddy.TestFunc');
