<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace buddy\tests;

use \buddy\Suite;
use \buddy\Spec;
use \php\Boot;

/**
 * Used for Buddy to test itself
 */
class SelfTest {
	/**
	 * @var Spec
	 */
	static public $lastSpec;
	/**
	 * @var Suite
	 */
	static public $lastSuite;

}

Boot::registerClass(SelfTest::class, 'buddy.tests.SelfTest');
