<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace logipar;

use \php\Boot;

class Token {
	/**
	 * @var string
	 */
	const AND = "AND";
	/**
	 * @var string
	 */
	const CLOSE = "CLOSE";
	/**
	 * @var string
	 */
	const LITERAL = "LITERAL";
	/**
	 * @var string
	 */
	const NOT = "NOT";
	/**
	 * @var string
	 */
	const OPEN = "OPEN";
	/**
	 * @var string
	 */
	const OR = "OR";
	/**
	 * @var string
	 */
	const XOR = "XOR";

	/**
	 * @var string
	 */
	public $literal;
	/**
	 * @var string
	 */
	public $type;

	/**
	 * Instantiate!
	 * 
	 * @param string $type
	 * @param string $literal
	 * 
	 * @return void
	 */
	public function __construct ($type, $literal = null) {
		#src/logipar/Token.hx:28: characters 3-19
		$this->type = $type;
		#src/logipar/Token.hx:29: characters 3-25
		$this->literal = $literal;
	}

	/**
	 * What's the precedence of this token?  For, you know, order of operations and all that.
	 * 
	 * @return int
	 */
	public function precedence () {
		#src/logipar/Token.hx:37: characters 10-14
		$__hx__switch = ($this->type);
		if ($__hx__switch === "AND" || $__hx__switch === "NOT") {
			#src/logipar/Token.hx:39: characters 5-13
			return 2;
		} else if ($__hx__switch === "OR" || $__hx__switch === "XOR") {
			#src/logipar/Token.hx:41: characters 5-13
			return 1;
		} else {
			#src/logipar/Token.hx:43: characters 5-13
			return 0;
		}
	}

	/**
	 * In case we want to display tokens, this'll make that easier.
	 * 
	 * @return string
	 */
	public function toString () {
		#src/logipar/Token.hx:52: lines 52-53
		if ($this->type === "LITERAL") {
			#src/logipar/Token.hx:53: characters 4-42
			return "LITERAL(" . ($this->literal??'null') . ")";
		}
		#src/logipar/Token.hx:54: characters 3-31
		return \Std::string($this->type);
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(Token::class, 'logipar.Token');
