<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace haxe\ds;

use \php\Boot;
use \haxe\IMap;
use \php\_Boot\HxEnum;

/**
 * EnumValueMap allows mapping of enum value keys to arbitrary values.
 * Keys are compared by value and recursively over their parameters. If any
 * parameter is not an enum value, `Reflect.compare` is used to compare them.
 */
class EnumValueMap extends BalancedTree implements IMap {
	/**
	 * @return void
	 */
	public function __construct () {
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:31: lines 31-68
		parent::__construct();
	}

	/**
	 * @param mixed $k1
	 * @param mixed $k2
	 * 
	 * @return int
	 */
	public function compare ($k1, $k2) {
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:34: characters 3-41
		$d = Boot::dynamicField($k1, 'index') - Boot::dynamicField($k2, 'index');
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:35: characters 3-23
		if ($d !== 0) {
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:35: characters 15-23
			return $d;
		}
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:36: characters 3-31
		$p1 = \Array_hx::wrap(Boot::dynamicField($k1, 'params'));
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:37: characters 3-31
		$p2 = \Array_hx::wrap(Boot::dynamicField($k2, 'params'));
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:38: characters 3-49
		if (($p1->length === 0) && ($p2->length === 0)) {
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:38: characters 41-49
			return 0;
		}
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:39: characters 3-29
		return $this->compareArgs($p1, $p2);
	}

	/**
	 * @param mixed $v1
	 * @param mixed $v2
	 * 
	 * @return int
	 */
	public function compareArg ($v1, $v2) {
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:53: lines 53-59
		if (($v1 instanceof HxEnum) && ($v2 instanceof HxEnum)) {
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:54: characters 4-19
			return $this->compare($v1, $v2);
		} else if (($v1 instanceof \Array_hx) && ($v2 instanceof \Array_hx)) {
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:56: characters 4-23
			return $this->compareArgs($v1, $v2);
		} else {
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:58: characters 4-27
			return \Reflect::compare($v1, $v2);
		}
	}

	/**
	 * @param \Array_hx $a1
	 * @param \Array_hx $a2
	 * 
	 * @return int
	 */
	public function compareArgs ($a1, $a2) {
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:43: characters 3-34
		$ld = $a1->length - $a2->length;
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:44: characters 3-25
		if ($ld !== 0) {
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:44: characters 16-25
			return $ld;
		}
		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:45: lines 45-48
		$_g = 0;
		$_g1 = $a1->length;
		while ($_g < $_g1) {
			$i = $_g++;
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:46: characters 4-37
			$d = $this->compareArg(($a1->arr[$i] ?? null), ($a2->arr[$i] ?? null));
			#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:47: characters 4-24
			if ($d !== 0) {
				#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:47: characters 16-24
				return $d;
			}
		}

		#C:\HaxeToolkit\haxe\std/haxe/ds/EnumValueMap.hx:49: characters 3-11
		return 0;
	}
}

Boot::registerClass(EnumValueMap::class, 'haxe.ds.EnumValueMap');
