<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace haxe\ds;

use \php\Boot;

/**
 * A tree node of `haxe.ds.BalancedTree`.
 */
class TreeNode {
	/**
	 * @var int
	 */
	public $_height;
	/**
	 * @var mixed
	 */
	public $key;
	/**
	 * @var TreeNode
	 */
	public $left;
	/**
	 * @var TreeNode
	 */
	public $right;
	/**
	 * @var mixed
	 */
	public $value;

	/**
	 * @param TreeNode $l
	 * @param mixed $k
	 * @param mixed $v
	 * @param TreeNode $r
	 * @param int $h
	 * 
	 * @return void
	 */
	public function __construct ($l, $k, $v, $r, $h = -1) {
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:236: lines 236-245
		if ($h === null) {
			$h = -1;
		}
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:237: characters 3-11
		$this->left = $l;
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:238: characters 3-10
		$this->key = $k;
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:239: characters 3-12
		$this->value = $v;
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:240: characters 3-12
		$this->right = $r;
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:241: lines 241-244
		if ($h === -1) {
			#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 14-95
			$tmp = null;
			#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 15-32
			$_this = $this->left;
			#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 35-53
			$_this1 = $this->right;
			#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 14-95
			if ((($_this === null ? 0 : $_this->_height)) > (($_this1 === null ? 0 : $_this1->_height))) {
				#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 56-73
				$_this2 = $this->left;
				#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 14-95
				$tmp = ($_this2 === null ? 0 : $_this2->_height);
			} else {
				#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 76-94
				$_this3 = $this->right;
				#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 14-95
				$tmp = ($_this3 === null ? 0 : $_this3->_height);
			}
			#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:242: characters 4-99
			$this->_height = $tmp + 1;
		} else {
			#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:244: characters 4-15
			$this->_height = $h;
		}
	}

	/**
	 * @return string
	 */
	public function toString () {
		#C:\HaxeToolkit\haxe\std/haxe/ds/BalancedTree.hx:250: characters 3-118
		return ((($this->left === null ? "" : ($this->left->toString()??'null') . ", "))??'null') . (("" . (\Std::string($this->key)??'null') . "=" . (\Std::string($this->value)??'null'))??'null') . ((($this->right === null ? "" : ", " . ($this->right->toString()??'null')))??'null');
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(TreeNode::class, 'haxe.ds.TreeNode');
