<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Anonymous objects implementation
 */
class HxAnon extends \StdClass {
	/**
	 * @param mixed $fields
	 * 
	 * @return void
	 */
	public function __construct ($fields = null) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:907: lines 907-912
		$_gthis = $this;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:908: characters 3-10
		;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:909: lines 909-911
		if ($fields !== null) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:910: characters 4-84
			foreach ($fields as $key => $value) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:910: characters 65-69
				$tmp = $_gthis;
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:910: characters 49-83
				$tmp->{$key} = $value;
			}
		}
	}

	/**
	 * @param string $name
	 * @param mixed $args
	 * 
	 * @return mixed
	 */
	public function __call ($name, $args) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:921: characters 3-57
		return ($this->$name)(...$args);
	}

	/**
	 * @param string $name
	 * 
	 * @return mixed
	 */
	public function __get ($name) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:916: characters 3-14
		return null;
	}
}

Boot::registerClass(HxAnon::class, 'php._Boot.HxAnon');
