<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Base class for enum types
 */
class HxEnum {
	/**
	 * @var int
	 */
	public $index;
	/**
	 * @var mixed
	 */
	public $params;
	/**
	 * @var string
	 */
	public $tag;

	/**
	 * @param string $tag
	 * @param int $index
	 * @param mixed $arguments
	 * 
	 * @return void
	 */
	public function __construct ($tag, $index, $arguments = null) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:675: characters 3-17
		$this->tag = $tag;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:676: characters 3-21
		$this->index = $index;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:677: characters 12-63
		$tmp = null;
		if ($arguments === null) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:677: characters 33-50
			$this1 = [];
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:677: characters 12-63
			$tmp = $this1;
		} else {
			$tmp = $arguments;
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:677: characters 3-63
		$this->params = $tmp;
	}

	/**
	 * PHP magic method to get string representation of this `Class`
	 * 
	 * @return string
	 */
	public function __toString () {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:692: characters 3-20
		$result = $this->tag;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:693: lines 693-696
		if (count($this->params) > 0) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:694: characters 4-88
			$strings = array_map(function ($item) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:694: characters 51-78
				return Boot::stringify($item);
			}, $this->params);
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:695: characters 4-54
			$result = ($result??'null') . "(" . (implode(",", $strings)??'null') . ")";
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:697: characters 3-16
		return $result;
	}

	/**
	 * Get string representation of this `Class`
	 * 
	 * @return string
	 */
	public function toString () {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:684: characters 3-22
		return $this->__toString();
	}
}

Boot::registerClass(HxEnum::class, 'php._Boot.HxEnum');
