<?php
/**
 * Generated by Haxe 4.0.0-rc.3+e3df7a448
 */

namespace php\_Boot;

use \php\Boot;

/**
 * Special exception which is used to wrap non-throwable values
 */
class HxException extends \Exception {
	/**
	 * @var mixed
	 */
	public $e;

	/**
	 * @param mixed $e
	 * 
	 * @return void
	 */
	public function __construct ($e) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:1009: characters 4-14
		$this->e = $e;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:1010: characters 4-28
		parent::__construct(Boot::stringify($e));
	}
}

Boot::registerClass(HxException::class, 'php._Boot.HxException');
