<?php
/**
 * Generated by Haxe 4.0.0-rc.3+e3df7a448
 */

namespace php\_Boot;

use \php\Boot;

/**
 * `String` implementation
 */
class HxString {
	/**
	 * @param string $str
	 * @param int $index
	 * 
	 * @return string
	 */
	static public function charAt ($str, $index) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:730: characters 10-58
		if ($index < 0) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:730: characters 22-24
			return "";
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:730: characters 27-58
			return mb_substr($str, $index, 1);
		}
	}

	/**
	 * @param string $str
	 * @param int $index
	 * 
	 * @return int
	 */
	static public function charCodeAt ($str, $index) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:734: lines 734-736
		if (($index < 0) || ($str === "")) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:735: characters 4-15
			return null;
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:737: lines 737-739
		if ($index === 0) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:738: characters 11-30
			$code = ord($str[0]);
			if ($code < 192) {
				return $code;
			} else if ($code < 224) {
				return (($code - 192) << 6) + ord($str[1]) - 128;
			} else if ($code < 240) {
				return (($code - 224) << 12) + ((ord($str[1]) - 128) << 6) + ord($str[2]) - 128;
			} else {
				return (($code - 240) << 18) + ((ord($str[1]) - 128) << 12) + ((ord($str[2]) - 128) << 6) + ord($str[3]) - 128;
			}
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:740: characters 3-46
		$char = mb_substr($str, $index, 1);
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:741: characters 10-50
		if ($char === "") {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:741: characters 23-27
			return null;
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:741: characters 30-50
			$code1 = ord($char[0]);
			if ($code1 < 192) {
				return $code1;
			} else if ($code1 < 224) {
				return (($code1 - 192) << 6) + ord($char[1]) - 128;
			} else if ($code1 < 240) {
				return (($code1 - 224) << 12) + ((ord($char[1]) - 128) << 6) + ord($char[2]) - 128;
			} else {
				return (($code1 - 240) << 18) + ((ord($char[1]) - 128) << 12) + ((ord($char[2]) - 128) << 6) + ord($char[3]) - 128;
			}
		}
	}

	/**
	 * @param int $code
	 * 
	 * @return string
	 */
	static public function fromCharCode ($code) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:836: characters 3-29
		return mb_chr($code);
	}

	/**
	 * @param string $str
	 * @param string $search
	 * @param int $startIndex
	 * 
	 * @return int
	 */
	static public function indexOf ($str, $search, $startIndex = null) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:745: lines 745-758
		if ($startIndex === null) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:746: characters 4-18
			$startIndex = 0;
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:748: characters 4-28
			$length = mb_strlen($str);
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:749: lines 749-754
			if ($startIndex < 0) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:750: characters 5-25
				$startIndex += $length;
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:751: lines 751-753
				if ($startIndex < 0) {
					#C:\HaxeToolkit\haxe\std/php/Boot.hx:752: characters 6-20
					$startIndex = 0;
				}
			}
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:755: lines 755-757
			if (($startIndex >= $length) && ($search !== "")) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:756: characters 5-14
				return -1;
			}
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:759: lines 759-764
		$index = null;
		if ($search === "") {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:760: characters 4-28
			$length1 = mb_strlen($str);
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:759: lines 759-764
			$index = ($startIndex > $length1 ? $length1 : $startIndex);
		} else {
			$index = mb_strpos($str, $search, $startIndex);
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:765: characters 10-39
		if ($index === false) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:765: characters 28-30
			return -1;
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:765: characters 33-38
			return $index;
		}
	}

	/**
	 * @param string $str
	 * @param string $search
	 * @param int $startIndex
	 * 
	 * @return int
	 */
	static public function lastIndexOf ($str, $search, $startIndex = null) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:769: characters 3-26
		$start = $startIndex;
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:770: lines 770-782
		if ($start === null) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:771: characters 4-13
			$start = 0;
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:773: characters 4-28
			$length = mb_strlen($str);
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:774: lines 774-781
			if ($start >= 0) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:775: characters 5-27
				$start -= $length;
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:776: lines 776-778
				if ($start > 0) {
					#C:\HaxeToolkit\haxe\std/php/Boot.hx:777: characters 6-15
					$start = 0;
				}
			} else if ($start < -$length) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:780: characters 5-20
				$start = -$length;
			}
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:783: lines 783-788
		$index = null;
		if ($search === "") {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:784: characters 4-28
			$length1 = mb_strlen($str);
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:783: lines 783-788
			$index = (($startIndex === null) || ($startIndex > $length1) ? $length1 : $startIndex);
		} else {
			$index = mb_strrpos($str, $search, $start);
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:789: lines 789-793
		if ($index === false) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:790: characters 4-13
			return -1;
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:792: characters 4-16
			return $index;
		}
	}

	/**
	 * @param string $str
	 * @param string $delimiter
	 * 
	 * @return \Array_hx
	 */
	static public function split ($str, $delimiter) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:797: lines 797-802
		$arr = null;
		if ($delimiter === "") {
			$arr = preg_split("//u", $str, -1, PREG_SPLIT_NO_EMPTY);
		} else {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:800: characters 4-49
			$delimiter = preg_quote($delimiter, "/");
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:797: lines 797-802
			$arr = preg_split("/" . ($delimiter??'null') . "/", $str);
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:803: characters 3-41
		return \Array_hx::wrap($arr);
	}

	/**
	 * @param string $str
	 * @param int $pos
	 * @param int $len
	 * 
	 * @return string
	 */
	static public function substr ($str, $pos, $len = null) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:807: characters 3-41
		return mb_substr($str, $pos, $len);
	}

	/**
	 * @param string $str
	 * @param int $startIndex
	 * @param int $endIndex
	 * 
	 * @return string
	 */
	static public function substring ($str, $startIndex, $endIndex = null) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:811: lines 811-816
		if ($endIndex === null) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:812: lines 812-814
			if ($startIndex < 0) {
				#C:\HaxeToolkit\haxe\std/php/Boot.hx:813: characters 5-19
				$startIndex = 0;
			}
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:815: characters 4-44
			return mb_substr($str, $startIndex);
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:817: lines 817-819
		if ($endIndex < 0) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:818: characters 4-16
			$endIndex = 0;
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:820: lines 820-822
		if ($startIndex < 0) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:821: characters 4-18
			$startIndex = 0;
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:823: lines 823-827
		if ($startIndex > $endIndex) {
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:824: characters 4-23
			$tmp = $endIndex;
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:825: characters 4-25
			$endIndex = $startIndex;
			#C:\HaxeToolkit\haxe\std/php/Boot.hx:826: characters 4-20
			$startIndex = $tmp;
		}
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:828: characters 3-66
		return mb_substr($str, $startIndex, $endIndex - $startIndex);
	}

	/**
	 * @param string $str
	 * 
	 * @return string
	 */
	static public function toLowerCase ($str) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:726: characters 3-35
		return mb_strtolower($str);
	}

	/**
	 * @param string $str
	 * 
	 * @return string
	 */
	static public function toString ($str) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:832: characters 3-13
		return $str;
	}

	/**
	 * @param string $str
	 * 
	 * @return string
	 */
	static public function toUpperCase ($str) {
		#C:\HaxeToolkit\haxe\std/php/Boot.hx:722: characters 3-35
		return mb_strtoupper($str);
	}
}

Boot::registerClass(HxString::class, 'php._Boot.HxString');
