<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace haxe\_Int32;

use \php\Boot;

final class Int32_Impl_ {
	/**
	 * @var int
	 */
	static public $extraBits;

	/**
	 * Compare `a` and `b` in unsigned mode.
	 * 
	 * @param int $a
	 * @param int $b
	 * 
	 * @return int
	 */
	static public function ucompare ($a, $b) {
		#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:227: lines 227-228
		if ($a < 0) {
			#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:228: characters 11-34
			if ($b < 0) {
				#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:228: characters 19-30
				return ((((~$b << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits) - ((~$a << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits)) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
			} else {
				#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:228: characters 33-34
				return 1;
			}
		}
		#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:229: characters 10-30
		if ($b < 0) {
			#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:229: characters 18-20
			return -1;
		} else {
			#C:\HaxeToolkit\haxe\std/haxe/Int32.hx:229: characters 23-30
			return (($a - $b) << Int32_Impl_::$extraBits) >> Int32_Impl_::$extraBits;
		}
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$extraBits = PHP_INT_SIZE * 8 - 32;
	}
}

Boot::registerClass(Int32_Impl_::class, 'haxe._Int32.Int32_Impl_');
Int32_Impl_::__hx__init();
