<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

namespace haxe;

use \php\Boot;

/**
 * Log primarily provides the `trace()` method, which is invoked upon a call to
 * `trace()` in Haxe code.
 */
class Log {
	/**
	 * @var \Closure
	 * Outputs `v` in a platform-dependent way.
	 * The second parameter `infos` is injected by the compiler and contains
	 * information about the position where the `trace()` call was made.
	 * This method can be rebound to a custom function:
	 * var oldTrace = haxe.Log.trace; // store old function
	 * haxe.Log.trace = function(v, ?infos) {
	 * // handle trace
	 * }
	 * ...
	 * haxe.Log.trace = oldTrace;
	 * If it is bound to null, subsequent calls to `trace()` will cause an
	 * exception.
	 */
	static public $trace;

	/**
	 * Format the output of `trace` before printing it.
	 * 
	 * @param mixed $v
	 * @param object $infos
	 * 
	 * @return string
	 */
	static public function formatOutput ($v, $infos) {
		#C:\HaxeToolkit\haxe\std/haxe/Log.hx:34: characters 3-27
		$str = \Std::string($v);
		#C:\HaxeToolkit\haxe\std/haxe/Log.hx:35: lines 35-36
		if ($infos === null) {
			#C:\HaxeToolkit\haxe\std/haxe/Log.hx:36: characters 4-14
			return $str;
		}
		#C:\HaxeToolkit\haxe\std/haxe/Log.hx:37: characters 3-54
		$pstr = ($infos->fileName??'null') . ":" . ($infos->lineNumber??'null');
		#C:\HaxeToolkit\haxe\std/haxe/Log.hx:38: characters 3-111
		if (($infos !== null) && ($infos->customParams !== null)) {
			#C:\HaxeToolkit\haxe\std/haxe/Log.hx:38: characters 53-111
			$_g = 0;
			$_g1 = $infos->customParams;
			while ($_g < $_g1->length) {
				#C:\HaxeToolkit\haxe\std/haxe/Log.hx:38: characters 58-59
				$v1 = ($_g1->arr[$_g] ?? null);
				#C:\HaxeToolkit\haxe\std/haxe/Log.hx:38: characters 53-111
				++$_g;
				#C:\HaxeToolkit\haxe\std/haxe/Log.hx:38: characters 84-111
				$str = ($str??'null') . ", " . (\Std::string($v1)??'null');
			}
		}
		#C:\HaxeToolkit\haxe\std/haxe/Log.hx:39: characters 3-23
		return ($pstr??'null') . ": " . ($str??'null');
	}

	/**
	 * @internal
	 * @access private
	 */
	static public function __hx__init ()
	{
		static $called = false;
		if ($called) return;
		$called = true;


		self::$trace = function ($v, $infos = null) {
			#C:\HaxeToolkit\haxe\std/haxe/Log.hx:61: characters 3-35
			$str = Log::formatOutput($v, $infos);
			#C:\HaxeToolkit\haxe\std/haxe/Log.hx:68: characters 3-19
			echo((\Std::string($str)??'null') . "\x0A");
		};
	}
}

Boot::registerClass(Log::class, 'haxe.Log');
Log::__hx__init();
