<?php
/**
 * Generated by Haxe 4.0.0-rc.3+e3df7a448
 */

namespace haxe;

use \php\Boot;

interface IMap {
	/**
	 * @return string
	 */
	public function toString () ;
}

Boot::registerClass(IMap::class, 'haxe.IMap');
