<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

use \php\Boot;
use \php\_Boot\HxEnum;

class Unary extends HxEnum {
	/**
	 * @return Unary
	 */
	static public function NOT () {
		static $inst = null;
		if (!$inst) $inst = new Unary('NOT', 0, []);
		return $inst;
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			0 => 'NOT',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'NOT' => 0,
		];
	}
}

Boot::registerClass(Unary::class, 'Unary');
