<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

use \php\Boot;
use \php\_Boot\HxEnum;

class Binary extends HxEnum {
	/**
	 * @return Binary
	 */
	static public function AND () {
		static $inst = null;
		if (!$inst) $inst = new Binary('AND', 0, []);
		return $inst;
	}

	/**
	 * @return Binary
	 */
	static public function OR () {
		static $inst = null;
		if (!$inst) $inst = new Binary('OR', 1, []);
		return $inst;
	}

	/**
	 * @return Binary
	 */
	static public function XOR () {
		static $inst = null;
		if (!$inst) $inst = new Binary('XOR', 2, []);
		return $inst;
	}

	/**
	 * Returns array of (constructorIndex => constructorName)
	 *
	 * @return string[]
	 */
	static public function __hx__list () {
		return [
			0 => 'AND',
			1 => 'OR',
			2 => 'XOR',
		];
	}

	/**
	 * Returns array of (constructorName => parametersCount)
	 *
	 * @return int[]
	 */
	static public function __hx__paramsCount () {
		return [
			'AND' => 0,
			'OR' => 0,
			'XOR' => 0,
		];
	}
}

Boot::registerClass(Binary::class, 'Binary');
