<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

use \php\Boot;

/**
 * The Date class provides a basic structure for date and time related
 * information. Date instances can be created by
 * - `new Date()` for a specific date,
 * - `Date.now()` to obtain information about the current time,
 * - `Date.fromTime()` with a given timestamp or
 * - `Date.fromString()` by parsing from a String.
 * There are some extra functions available in the `DateTools` class.
 * In the context of Haxe dates, a timestamp is defined as the number of
 * milliseconds elapsed since 1st January 1970.
 */
final class Date {
	/**
	 * @var float
	 */
	public $__t;

	/**
	 * @param float $t
	 * 
	 * @return Date
	 */
	static public function fromPhpTime ($t) {
		#C:\HaxeToolkit\haxe\std/php/_std/Date.hx:80: characters 3-41
		$d = new Date(2000, 1, 1, 0, 0, 0);
		#C:\HaxeToolkit\haxe\std/php/_std/Date.hx:81: characters 3-12
		$d->__t = $t;
		#C:\HaxeToolkit\haxe\std/php/_std/Date.hx:82: characters 3-11
		return $d;
	}

	/**
	 * Returns a Date from a formatted string `s`, with the following accepted
	 * formats:
	 * - `"YYYY-MM-DD hh:mm:ss"`
	 * - `"YYYY-MM-DD"`
	 * - `"hh:mm:ss"`
	 * The first two formats are expressed in local time, the third in UTC
	 * Epoch.
	 * 
	 * @param string $s
	 * 
	 * @return Date
	 */
	static public function fromString ($s) {
		#C:\HaxeToolkit\haxe\std/php/_std/Date.hx:92: characters 3-35
		return Date::fromPhpTime(strtotime($s));
	}

	/**
	 * Creates a new date object from the given arguments.
	 * The behaviour of a Date instance is only consistent across platforms if
	 * the the arguments describe a valid date.
	 * - month: 0 to 11
	 * - day: 1 to 31
	 * - hour: 0 to 23
	 * - min: 0 to 59
	 * - sec: 0 to 59
	 * 
	 * @param int $year
	 * @param int $month
	 * @param int $day
	 * @param int $hour
	 * @param int $min
	 * @param int $sec
	 * 
	 * @return void
	 */
	public function __construct ($year, $month, $day, $hour, $min, $sec) {
		#C:\HaxeToolkit\haxe\std/php/_std/Date.hx:31: characters 3-53
		$this->__t = mktime($hour, $min, $sec, $month + 1, $day, $year);
	}

	/**
	 * Returns the timestamp (in milliseconds) of the date. It might
	 * only have a per-second precision depending on the platforms.
	 * For measuring time differences with millisecond accuracy on
	 * all platforms, see `haxe.Timer.stamp`.
	 * 
	 * @return float
	 */
	public function getTime () {
		#C:\HaxeToolkit\haxe\std/php/_std/Date.hx:35: characters 3-22
		return $this->__t * 1000.0;
	}
}

Boot::registerClass(Date::class, 'Date');
