<?php
/**
 * Generated by Haxe 4.0.0-rc.2+77068e10c
 */

use \php\Boot;
use \php\_Boot\HxException;

class Node {
	/**
	 * @var Node
	 */
	public $left;
	/**
	 * @var Node
	 */
	public $right;
	/**
	 * @var \Token
	 */
	public $token;

	/**
	 * @param \Token $token
	 * 
	 * @return void
	 */
	public function __construct ($token) {
		#src/LogicString.hx:38: characters 3-21
		$this->token = $token;
	}

	/**
	 * @param mixed $a
	 * @param \Closure $f
	 * 
	 * @return bool
	 */
	public function check ($a, $f) {
		#src/LogicString.hx:61: characters 10-20
		$__hx__switch = ($this->token->type->index);
		if ($__hx__switch === 0) {
			#src/LogicString.hx:63: characters 12-47
			if ($this->left->check($a, $f)) {
				#src/LogicString.hx:63: characters 31-47
				return $this->right->check($a, $f);
			} else {
				#src/LogicString.hx:63: characters 12-47
				return false;
			}
		} else if ($__hx__switch === 1) {
			#src/LogicString.hx:65: characters 12-47
			if (!$this->left->check($a, $f)) {
				#src/LogicString.hx:65: characters 31-47
				return $this->right->check($a, $f);
			} else {
				#src/LogicString.hx:65: characters 12-47
				return true;
			}
		} else if ($__hx__switch === 2) {
			#src/LogicString.hx:67: characters 5-29
			$l = $this->left->check($a, $f);
			#src/LogicString.hx:68: characters 5-30
			$r = $this->right->check($a, $f);
			#src/LogicString.hx:69: characters 12-34
			if (!(!$l && $r)) {
				#src/LogicString.hx:69: characters 25-34
				if ($l) {
					#src/LogicString.hx:69: characters 31-33
					return !$r;
				} else {
					#src/LogicString.hx:69: characters 25-34
					return false;
				}
			} else {
				#src/LogicString.hx:69: characters 12-34
				return true;
			}
		} else if ($__hx__switch === 3) {
			#src/LogicString.hx:71: characters 5-29
			return !$this->right->check($a, $f);
		} else if ($__hx__switch === 6) {
			#src/LogicString.hx:73: characters 5-31
			return $f($a, $this->token->literal);
		} else {
			#src/LogicString.hx:75: characters 5-10
			throw new HxException("Unexpected token encountered.");
		}
	}

	/**
	 * @param \Closure $f
	 * 
	 * @return string
	 */
	public function fancyString ($f = null) {
		#src/LogicString.hx:45: characters 3-16
		$s = null;
		#src/LogicString.hx:46: lines 46-47
		if ($f !== null) {
			#src/LogicString.hx:47: characters 4-15
			$s = $f($this);
		}
		#src/LogicString.hx:48: lines 48-49
		if ($s !== null) {
			#src/LogicString.hx:49: characters 4-12
			return $s;
		}
		#src/LogicString.hx:50: characters 10-20
		$__hx__switch = ($this->token->type->index);
		if ($__hx__switch === 3) {
			#src/LogicString.hx:54: characters 5-32
			return "NOT(" . (\Std::string($this->right)??'null') . ")";
		} else if ($__hx__switch === 6) {
			#src/LogicString.hx:52: characters 5-37
			return "{" . ($this->token->literal??'null') . "}";
		} else {
			#src/LogicString.hx:56: characters 5-73
			return "(" . (\Std::string($this->left)??'null') . " " . (\Std::string($this->token->type)??'null') . " " . (\Std::string($this->right)??'null') . ")";
		}
	}

	/**
	 * @return string
	 */
	public function toString () {
		#src/LogicString.hx:42: characters 38-58
		return $this->fancyString();
	}

	public function __toString() {
		return $this->toString();
	}
}

Boot::registerClass(Node::class, 'Node');
